allowBuilds:
  esbuild: true
autoInstallPeers: false
minimumReleaseAgeExclude:
  - '@solspace/freeform-core@0.1.19'
  - '@solspace/freeform-extensions@0.1.19'
  - '@solspace/freeform-theme-bootstrap@0.1.19'
  - '@solspace/freeform-theme-default@0.1.19'
  - '@solspace/freeform-theme-tailwind@0.1.19'
  - '@solspace/freeform-vue@0.1.19'
peerDependencyRules:
  ignoreMissing:
    - "@solspace/freeform-react"
    - react
    - react-dom
